package dev.comfyfluffy.caustica.rt;

import dev.comfyfluffy.caustica.CausticaMod;
import dev.comfyfluffy.caustica.client.VanillaRenderController;
import dev.comfyfluffy.caustica.mixin.LevelRendererWeatherAccessor;
import dev.comfyfluffy.caustica.mixin.MinecraftAccessor;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.LevelRenderer;
import net.minecraft.client.renderer.state.level.LevelRenderState;
import net.minecraft.world.phys.Vec3;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

/**
 * Replays vanilla's extracted weather pass after the RT world has replaced the cancelled LevelRenderer.
 *
 * <p>Rain/snow streaks are not ParticleEngine particles in 26.2; they are generated by
 * WeatherEffectRenderer from LevelRenderState.weatherRenderState inside LevelRenderer's weather frame
 * pass. Caustica cancels LevelRenderer at HEAD, so those real vanilla columns never execute. This bridge
 * invokes that same renderer at the before-hand seam, after RtComposite has written the ray-traced world
 * into the main target. ParticleEngine splashes remain captured through RtEntities as before; the falling
 * columns now come from Minecraft's own weather extraction instead of a duplicate procedural TLAS mesh.
 */
public final class RtVanillaWeather {
    private static Method renderThreeArg;
    private static Method renderTwoArg;
    private static boolean warned;

    private RtVanillaWeather() {
    }

    public static void renderAfterRt(LevelRenderState levelRenderState) {
        if (levelRenderState == null || !VanillaRenderController.INSTANCE.wasWorldSkippedThisFrame()) {
            return;
        }
        Object weatherState = levelRenderState.weatherRenderState;
        if (weatherState == null) {
            return;
        }
        Minecraft mc = Minecraft.getInstance();
        LevelRenderer levelRenderer = ((MinecraftAccessor) mc).caustica$levelRenderer();
        if (levelRenderer == null) {
            return;
        }
        Object weatherRenderer = ((LevelRendererWeatherAccessor) levelRenderer).caustica$weatherEffectRenderer();
        if (weatherRenderer == null) {
            return;
        }
        Vec3 cameraPos = levelRenderState.cameraRenderState.pos;
        try {
            Method render = resolveRenderMethod(weatherRenderer.getClass(), weatherState.getClass());
            if (render == null) {
                warnOnce("Could not locate WeatherEffectRenderer.render(Vec3, WeatherRenderState[, LevelRenderState])");
                return;
            }
            if (render.getParameterCount() == 3) {
                render.invoke(weatherRenderer, cameraPos, weatherState, levelRenderState);
            } else {
                render.invoke(weatherRenderer, cameraPos, weatherState);
            }
        } catch (IllegalAccessException | InvocationTargetException | RuntimeException t) {
            warnOnce("Vanilla weather replay failed", t);
        }
    }

    private static Method resolveRenderMethod(Class<?> rendererClass, Class<?> weatherStateClass) {
        if (renderThreeArg != null || renderTwoArg != null) {
            return renderThreeArg != null ? renderThreeArg : renderTwoArg;
        }
        try {
            renderThreeArg = rendererClass.getMethod("render", Vec3.class, weatherStateClass, LevelRenderState.class);
            return renderThreeArg;
        } catch (NoSuchMethodException ignored) {
            // Older/dev mappings keep the two-argument method; try it below.
        }
        try {
            renderTwoArg = rendererClass.getMethod("render", Vec3.class, weatherStateClass);
            return renderTwoArg;
        } catch (NoSuchMethodException ignored) {
            return null;
        }
    }

    private static void warnOnce(String message) {
        if (!warned) {
            warned = true;
            CausticaMod.LOGGER.warn(message);
        }
    }

    private static void warnOnce(String message, Throwable t) {
        if (!warned) {
            warned = true;
            CausticaMod.LOGGER.warn(message, t);
        }
    }
}
